### ISSUE TITLE
Contao 5.x

### ISSUE THREAD

**Issue by sdahlmann** [erdmannfreunde/theme-toolbox#11]
When I install the extension "theme-toolbox" under Contao 5.0.3, I only get an error message in the Contao Manager when trying to install. Is an adjustment to Contao 5.x planned?

**Comment by denniserdmann** [comment]
Yes, there will be an update for contao 5. You can test the current develop-version by installing `dev-develop` instead of `latest-version`.

**Comment by sdahlmann** [comment]
When I select "dev-develop" in the Contao Manager, I get an error message on Contao 5.0.6. He takes the May dev version. Am I doing something wrong?
![Contao-dev](https://user-images.githubusercontent.com/17680074/204600018-6e2c6061-18b1-4e04-8f88-a99caf04fd27.png)
![toolbox-dev1](https://user-images.githubusercontent.com/17680074/204600045-a4f7cbb4-7c83-46e5-a0cf-756c4506280e.png)
![toolbox-dev2](https://user-images.githubusercontent.com/17680074/204600058-bdab4174-6dc2-4343-a945-c31ac9f3e3a0.png)

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires erdmannfreunde/theme-toolbox dev-develop -> satisfiable by erdmannfreunde/theme-toolbox[dev-develop].
    - erdmannfreunde/theme-toolbox dev-develop requires symfony/http-kernel ^5.0 -> found symfony/http-kernel[v5.0.0, ..., v5.4.16] but these were not loaded, likely because it conflicts with another require.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

**Comment by denniserdmann** [comment]
Die neue Version ist nun unter `2.x-dev` zu finden
