### ISSUE TITLE
Classes for News, Events and FAQs

### ISSUE THREAD

**Issue by Aybee** [erdmannfreunde/theme-toolbox#15]
Is it planned to also provide classes for News, Events and FAQs? I'm speaking about the basic settings of a News, Event or FAQ.

If not, is there another extension that does similar things including News, Events and FAQs?

**Comment by denniserdmann** [comment]
Nothing planned yet. 

> If not, is there another extension that does similar things including News, Events and FAQs?

I' not sure, you can test the [component-style-manager](https://github.com/oveleon/contao-component-style-manager)

**Comment by Aybee** [comment]
Ok, thank you. I already tried this extension and like it, but I'm missing the feature to deactivate SCSS cache in there. So now I have to install both extensions? Or is there another easy way to bring in this SCSS cache feature?

**Comment by christianbarkowsky** [comment]
Done @denniserdmann @Aybee just try 🚀 
Branche feature/15-lasses-for-news-events-faqs

**Comment by denniserdmann** [comment]
I tested some cases for news, events and faq and here are the results:

- News - List ✅
- News - Reader ✅
- Events - List ❌
- Events - Reader ✅
- FAQ - Page ❌
- FAQ - List ❌
- FAQ - Reader ✅

@christianbarkowsky Can you check/add the classes for the missing modules?

**Comment by christianbarkowsky** [comment]
yes, i will do @denniserdmann

**Comment by christianbarkowsky** [comment]
Please try again @denniserdmann

**Comment by denniserdmann** [comment]
Nothing changed for me. It looks like yo try to solve another problem. Just to make sure, we're working on the same problem, an example:

I have a fe-module with 5 events. I gave the third event an extra class and want to style this item differently than the rest (for example a larger image). So in my event list, this events should have an additional class (full class list: `event layout_list upcoming cal_1 event--highlight`)

Is this working with your changes? If not, maybe it has something to do with de markup itself (and therefor the classes can not be added).

**Comment by christianbarkowsky** [comment]
News & events works now @denniserdmann

**Comment by denniserdmann** [comment]
@christianbarkowsky i will check this on friday
