### ISSUE TITLE
Contao 5.2: fehlende Auswahl für Redakteure

### ISSUE THREAD

**Issue by rustykowski** [erdmannfreunde/theme-toolbox#16]
Unter Contao 5.2 ist es mir bisher noch nicht gelungen, die Stilauswahl für Redakteure sichtbar zu machen. Bisher ist sie nur für Admins sichtbar. Das betrifft sowohl Artikel als auch Inhaltselemente (Formularfelder, Nachrichten + FAQ habe ich nicht probiert).

Habe ich bei den Einstellungen der Benutzergruppe etwas vergessen?

<img width="227" alt="image" src="https://github.com/erdmannfreunde/theme-toolbox/assets/1775048/c5d8a786-e8e9-4a91-afb6-c90c85b674e4">

**Comment by christianbarkowsky** [comment]
Du hast nicht vergessen @rustykowski 
Ich arbeite gerade an einer Lösung.

**Comment by christianbarkowsky** [comment]
Bitte mal im Branche 3.0 (https://github.com/erdmannfreunde/theme-toolbox/tree/3.0) testen @rustykowski @denniserdmann ... sieht soweit gut aus, vielleicht findet ihr ja noch was. N8

**Comment by rustykowski** [comment]
Version 3.0.0 war bei mir bereits installiert. Dort wird wie gesagt keine Stilauswahl angezeigt, wenn man nicht als Admin eingeloggt ist. Oder hast du schon eine 3.0.1 released?

**Comment by christianbarkowsky** [comment]
Du mussten den aktuelle Code ziehen - keine Version. Wenn alles passt, geht die 3.0.1 raus. @rustykowski

**Comment by rustykowski** [comment]
yep, sieht gut aus! Ich habe jetzt in der Benutzergruppenkonfiguration unter „Erlaubte Felder“ neue Felder namens „CSS Toolbox [toolbox_permissions]“ vorgefunden. Damit konnte ich das Feature für Redakteure aktivieren.

**Comment by christianbarkowsky** [comment]
Genau so ist das gedacht @rustykowski 
Dann geht gleich die 3.0.1 an den Start.
Danke für deine Issue. 🙏

**Comment by rustykowski** [comment]
Bestens, danke @christianbarkowsky !

**Comment by christianbarkowsky** [comment]
Released @rustykowski
