### ISSUE TITLE
Fehlende Sprachvariabel für legend

### ISSUE THREAD

**Issue by chwchw** [erdmannfreunde/theme-toolbox#17]
Backend-Url: contao?do=toolboxEditor&act=edit

Contao-Version: 5.3.x

<img width="368" alt="Screenshot 2024-02-02 at 11 21 47" src="https://github.com/erdmannfreunde/theme-toolbox/assets/8430041/1a504d78-0d94-45fe-8cf4-62d3821bd9dc">

**Comment by christianbarkowsky** [comment]
Wird erledigt @chwchw
