### ISSUE TITLE
Bezeichnung für classes des keyValueWizard optimieren

### ISSUE THREAD

**Issue by chwchw** [erdmannfreunde/theme-toolbox#19]
Ohne den Erklärungstext zu lesen ist nicht ersichtlich was mit Schlüssel und Wert gemeint ist.

**Änderungsvorschläge:**
- Klassen -> CSS-Klassen
- Schlüssel -> CSS-Klasse
- Wert -> Bezeichnung oder Titel
- Bitte geben Sie die CSS-Klassen und ihre Übersetzung ein. -> Bitte geben Sie die CSS-Klassen und ihre/n Bezeichnung/Titel ein.
- Backend.Sie können -> Backend. Sie können

<img width="1135" alt="Screenshot 2024-02-03 at 10 31 19" src="https://github.com/erdmannfreunde/theme-toolbox/assets/8430041/28b86245-6155-4afe-95cb-1eb2a81c5ea1">
https://github.com/erdmannfreunde/theme-toolbox/blob/e620035c3b521d8c0f83e41ee7558482ae25c443/contao/dca/tl_toolbox_editor_css.php#L125

**Comment by christianbarkowsky** [comment]
@denniserdmann hier benötige ich deine Zuarbeit.

**Comment by denniserdmann** [comment]
Kann man für _keyValueWizard_ mittlerweile eigene Labels verwenden? Dann sollten wir das tun. Ich bin noch auf dem Stand, dass das nicht geht, aber scheinbar kommt der auch für das neue Description-List Element zum Einsatz. 

Von daher, können wir das wie von @chwchw vorgeschlagen umsetzen
