### ISSUE TITLE
Problem beim Speichern von Modulen nach Update auf 3.0.2 & Contao 5.3.0

### ISSUE THREAD

**Issue by Webstylerin** [erdmannfreunde/theme-toolbox#21]
Hallöchen,

ich habe heute im Laufe des Tages die neueste Version eurer Erweiterung installiert und kann seitdem leider keine Module mehr bearbeiten. Sobald ich den Typ ändere oder versuche zu speichern, kommt die folgende Meldung:

"An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'toolbox_classes' in 'field list'".

Ich denke, die Toolbox CSS-Klassen haben in den Modulen gar nichts zu suchen.

Ich habe auch ein Downgrade auf die 3.0.1 und 3.0.0 probiert, leider ohne Erfolg. Aktuell ist es mir nicht möglich, irgendein Modul zu bearbeiten.

Liebe Grüße
Nicole

**Comment by christianbarkowsky** [comment]
Ist deine DB aktuell? @Webstylerin

**Comment by denniserdmann** [comment]
Moin Nicole,
hast du die Datenbank aktualisiert? Dann müssten die neuen Spalten angelegt werden und das Problem behoben sein.

> Ich denke, die Toolbox CSS-Klassen haben in den Modulen gar nichts zu suchen.

Eigentlich soll es dadurch möglich sein, dass auch Modulen Klassen gegeben werden können, allerdings habe ich gerade ebenfalls ein Problem damit, dass die Klassen auch ausgegeben werden.

@christianbarkowsky Kannst du dir das mal ansehen, warum die Klassen nicht ergänzt werden?

**Comment by Webstylerin** [comment]
Hi ihr zwei,

ja, DB mehrfach aktualisiert: "Keine ausstehenden Migrationen oder Schema-Änderungen gefunden…"

**Comment by christianbarkowsky** [comment]
Ich kümmere mich @Webstylerin  @denniserdmann

**Comment by denniserdmann** [comment]
@Webstylerin Kannst du mir vielleicht noch beschreiben, wie es zu dem Problem gekommen ist? 

Ich hatte vorhin eine frische Contao 5.3 Installation aufgesetzt und keine Probleme. War das eine bestehende Contao 5.2 Installation, die auf 5.3 angehoben wurde? Oder hast du in einer bestehenden 5.3 (die auch schon Module hatte) die Erweiterung installiert und danach kam es zum dem Fehler? 

Ich möchte das Problem einfach besser eingrenzen können, falls es noch bei anderen Personen auftritt.

**Comment by Webstylerin** [comment]
Klar. Die Installation ist noch recht neu, war eine frische 5.3.dev und ist mittlerweile auf die 5.3.0 upgedatet. Ich habe heute schon mit Modulen und der Toolbox gearbeitet und habe dann eine Erweiterung entfernt, weil ich gemerkt habe, ich brauche sie nicht. Dabei habe ich alle Pakete aktualisiert und damit wohl die neue Version der Toolbox bekommen. Als ich dann wieder zu den Modulen gekommen bin, gabs das Problem. Habe, wie gesagt, versucht auf die 3.0.1 bzw. .0 zurück zu fallen, hat nicht geholfen, es wurden keine DB Updates angeboten und der Fehler ist geblieben.

Das ist aktuell installiert:
"contao/manager-bundle": "5.3.*",
"erdmannfreunde/theme-toolbox": "^3.0",
"numero2/contao-proper-filenames": "^2.1"

Ansonsten ist mir der Manager heute bei einer Aktualisierung mal ins Leere gelaufen. Es waren wohl kurz die Cloud-Server ausgelastet und bei mir ging die Aktualisierung nicht weiter. Habe dann die task.json gelöscht, dann ging wieder alles. Denke aber nicht, dass das etwas damit zu tun hat, oder? Zwischenzeitlich ist der Manager ja mehrfach durchgelaufen.
