### ISSUE TITLE
Mehrere Klassen übergeben möglich?

### ISSUE THREAD

**Issue by denniserdmann** [erdmannfreunde/theme-toolbox#3]
Ich würde gerne über die Auswahl einem Element/Artikel mehr als eine Klassen zuweisen. Ist das möglich? 

Beispiel: Links als Button dazustellen erfordert aktuell zwei Klassen: `btn btn--primary`. Es wäre eine Erleichterung, wenn ich am Element nur „Button Primärfarbe“ auswählen müsste und die Toolbox beide Klassen hinzufügt.

Ist das möglich?

**Comment by richardhj** [comment]
Du kannst die CSS-Klassen entsprechend konfigurieren und die Änderung in f5986624dcb34e9ccd53613a0bb225da865eeba4 sorgt dafür, dass die Klasse "btn" dann nur einmal ausgeben wird.

![Screenshot 2021-11-01 at 09 44 23](https://user-images.githubusercontent.com/1284725/139645531-0534c80e-9df2-41d0-addc-d33f959bb07d.png)

**Comment by denniserdmann** [comment]
Danke. Ich schauen es mir morgen an und gebe dir Rückmeldung.

**Comment by denniserdmann** [comment]
released in  Version 2.1.0
