### ISSUE TITLE
Klassen über „Mehrere bearbeiten“ zuweisen möglich?

### ISSUE THREAD

**Issue by denniserdmann** [erdmannfreunde/theme-toolbox#4]
Ist es möglich, dass wir die dynamisch erzeugten Felder im Modus „Mehrere bearbeiten“ ebenfalls anzeigen können?

Beispiel: Ich möchte 5 Text-Elementen eine Klasse „text--highlight“ geben. Das ginge am Einfachsten über die Stapelbearbeitung in Contao, allerdings werden die Felder der Toolbox nicht zur Auswahl angeboten (weil sie vermutlich dynamisch geladen werden).

Gibt es eine Möglichkeit, sie dennoch anzuzeigen (auch auf die Gefahr hin, dass man Auswahl-Möglichkeiten hat, die eigentlich nicht gehen sollten)?

**Comment by richardhj** [comment]
Fixed in eea8b766b562579e6f40c4835bd426cc02d3b6ce.
