### ISSUE TITLE
Error: Attempted to call an undefined method named "executeQuery" of class "Doctrine\DBAL\Query\QueryBuilder"

### ISSUE THREAD

**Issue by mlwebworker** [erdmannfreunde/theme-toolbox#6]
Erhalte in einer Installation den oben genannten Fehler beim Bearbeiten einzelner Inhaltselemente. Scheint vom Typ des Inhaltselement unabhängig zu sein.

Contao 4.12.7 
erdmannfreunde/theme-toolbox 2.1.1
PHP 7.4.27

Hier der komplette Stacktrace

```
Symfony\Component\ErrorHandler\Error\UndefinedMethodError:
Attempted to call an undefined method named "executeQuery" of class "Doctrine\DBAL\Query\QueryBuilder".

  at vendor/erdmannfreunde/theme-toolbox/src/EventListener/DataContainer/RegisterFieldsInPaletteListener.php:50
  at ErdmannFreunde\ThemeToolboxBundle\EventListener\DataContainer\RegisterFieldsInPaletteListener->onLoadContentCallback()
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:203)
  at Contao\DC_Table->__construct()
     (vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:415)
  at Contao\Backend->getBackendModule()
     (vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:169)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:49)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:152)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (web/index.php:31)     
```

Kleiner Hinweis. Ich habe diese Installation gerade übernommen und bin noch am Beseitigen diverser Altlasten. Ich kann nicht mit Sicherheit sagen, ob es da noch Wechselwirkung mir irgendetwas gibt.

**Comment by richardhj** [comment]
Problem gelöst. Da zwischen Contao 4.12 und 4.13 verschiedene Doctrine-Versionen verlangt werden, ignorieren wir jetzt einfach mal die Deprecations in Contao 4.13. Siehe bba15108c199c9b581d06d581446c1394122e967.

**Comment by denniserdmann** [comment]
Aber mit dem Revert ist die Erweiterung aktuell unter Contao 4.13 nicht nutzbar, denn in 4.13 gibt es nun wieder folgende Fehlermeldung: 

```
Attempted to call an undefined method named "fetchColumn" of class "Doctrine\DBAL\Result".
```

Sofern wir nicht mit einer Versionsabfrage und Weiche arbeiten können, sollten wir vielleicht eine neue Minor-Version, die Contao 4.13 voraussetzt veröffentlichen.

@richardhj Was denkst du?

**Comment by richardhj** [comment]
Closed in b4be70fe1fb83aae536e6cf17c17cea2f10f3f34.

**Comment by Aybee** [comment]
Nur zur Info.

Ich muss gerade vorübergehend noch in Contao 4.9.37 auf PHP 7.4.33 die theme-toolbox installieren.

Ich bekam den gleichen Fehler.

Die einzige Version die in dieser Umgebung zu installieren ist, ist wohl die 2.1.1.

Mit der Anpassung von oben https://github.com/erdmannfreunde/theme-toolbox/issues/6#issuecomment-1050130551 ist die Fehlermeldung jetzt erstmal weg.

Ich melde mich, wenn es noch weitere Fehler gibt.

Achso, und vielen Dank für diese tolle Erweiterung 👍
