### ISSUE TITLE
HTTP 500 Internal Server Error beim Aufrufen der Inhaltselemente

### ISSUE THREAD

**Issue by Brezosisus** [erdmannfreunde/theme-toolbox#8]
Hallo, habe diesen Fehler unter Contao Version 4.13 mit Theme Toolbox Version 2.2.1. Nachdem ich ein im Toolbox-Editor angelegtes Feld unter "Anwendungsbereich" für z.B. Inhaltselemente freigebe, kann ich diese Inhaltselemente im Backend nicht mehr aufrufen. Ich erhalte einen HTTP 500 Internal Server Error:

**TypeError**
> preg_match() expects parameter 2 to be string, null given
> 
> at vendor/erdmannfreunde/theme-toolbox/src/EventListener/DataContainer/SaveClasses.php:80
> at preg_match()
> (vendor/erdmannfreunde/theme-toolbox/src/EventListener/DataContainer/SaveClasses.php:80)
> at ErdmannFreunde\ThemeToolboxBundle\EventListener\Da taContainer\SaveClasses::ErdmannFreunde\ThemeToolb oxBundle\EventListener\DataContainer\{closure}()
> at array_filter()
> (vendor/erdmannfreunde/theme-toolbox/src/EventListener/DataContainer/SaveClasses.php:80)
> at ErdmannFreunde\ThemeToolboxBundle\EventListener\Da taContainer\SaveClasses->onLoadCallback()
> (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:1931)
> at Contao\DC_Table->edit()
> (vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:655)
> at Contao\Backend->getBackendModule()
> (vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:170)
> at Contao\BackendMain->run()
> (vendor/contao/core-bundle/src/Controller/BackendController.php:49)
> at Contao\CoreBundle\Controller\BackendController->mainAction()
> (vendor/symfony/http-kernel/HttpKernel.php:152)
> at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
> (vendor/symfony/http-kernel/HttpKernel.php:74)
> at Symfony\Component\HttpKernel\HttpKernel->handle()
> (vendor/symfony/http-kernel/Kernel.php:202)
> at Symfony\Component\HttpKernel\Kernel->handle()
> (web/index.php:44)
> at require('/srv/www/.../public/web/index.php')
> (web/app.php:13)

**Logs**
> Level Channel Message
> INFO 10:50:59 php User Deprecated: Since symfony/framework-bundle 5.3: The "session.storage.factory.service" service is deprecated, use "session.storage.factory.native", "session.storage.factory.php_bridge" or "session.storage.factory.mock_file" instead.
> 
> {
> "exception": {}
> }
> 
> INFO 10:50:59 php User Deprecated: Since symfony/framework-bundle 5.3: The "session.storage.native" service is deprecated, use "session.storage.factory.native" instead.
> 
> {
> "exception": {}
> }
> 
> INFO 10:50:59 php User Deprecated: Since symfony/framework-bundle 5.3: The "session.storage.metadata_bag" service is deprecated, create your own "session.storage.factory" instead.
> 
> {
> "exception": {}
> }
> 
> INFO 10:50:59 php User Deprecated: Since contao/core-bundle 4.10: Using the "Contao\CoreBundle\Routing\FrontendLoader" class has been deprecated and will no longer work in Contao 5.0. Use Symfony routing instead.
> 
> {
> "exception": {}
> }
> 
> INFO 10:50:59 request Matched route "contao_backend".
> 
> {
> "route": "contao_backend",
> "route_parameters": {
> "_route": "contao_backend",
> "_scope": "backend",
> "_token_check": true,
> "_controller": "Contao\\CoreBundle\\Controller\\BackendController ::mainAction"
> },
> "request_uri": "https://www.....de/contao?act=edit&do=article&id=667&ref=Czf_3XfB&rt= 01df05316fe700460427299435dae0a.nqekr1XciQ9H5WNmSW llcvFnsE7nn7-7GiA2c2-ipqc.5P6TzWy13WQxnCweLiZWRYId3AKmqoriT1FnBiHF5eHzw fffMovfTh2vAA&table=tl_content",
> "method": "GET"
> }
> 
> DEBUG 10:50:59 security Read existing security token from the session.
> 
> {
> "key": "_security_contao_backend",
> "token_class": "Symfony\\Component\\Security\\Core\\Authenticatio n\\Token\\UsernamePasswordToken"
> 
> ...
> 
> }

**Comment by denniserdmann** [comment]
Vielen Dank für den Hinweis. Wir werden das prüfen und melden uns.
