### ISSUE TITLE
Contao 4.13 + RockSolid Custom Elements = Abschnitt "Toolbox CSS-Klassen" fehlt

### ISSUE THREAD

**Issue by Webstylerin** [erdmannfreunde/theme-toolbox#9]
Hallo,

ich nutze gerne den Toolbox-Editor auch im Zusammenhang mit meinen Custom Elements. Unter 4.9 kein Problem, unter 4.13 fehlt allerdings der Bereich "Toolbox CSS-Klassen". Normale Text-Elemente haben den Bereich für die Klassen-Auswahl an gewohnter Stelle.

Im Toolbox-Editor selbst sind die Custom Elemente unter Anwendungsbereich aktiviert.

Fehlt hier noch etwas zur 4.13-Kompatibilität oder gibt es jetzt noch einen weiteren Schritt, den ich tun muss?

LG
Nicole

![2022-03-15 15-04-32](https://user-images.githubusercontent.com/3033160/158396160-13825bbd-3315-41b3-8610-fcac7f76e12b.png)

**Comment by rabauss** [comment]
Maybe the loading order is the reason - so this bundle should be loaded after `RocksolidCustomElementsBundle`
https://github.com/erdmannfreunde/theme-toolbox/blob/ed6f186ce1fae5f6b42bfc23204e324778ab2e09/src/ContaoManager/Plugin.php#L33

**Comment by richardhj** [comment]
Wir sind in einem onload-Callback, deswegen sollte die Ladereihenfolge der Bundles keine Rolle spielen. 
Jetzt liegt es an der Reihenfolge der Callbacks.
Am besten jetzt nochmal probieren.

**Comment by Webstylerin** [comment]
Perfekt! Die CSS-Stile sind nun auch in den Custom Elements vorhanden. Herzlichen Dank!
